In [62]:
#main code 분석할 데이터를 만들어서 저장하는 file  ext to escape and save the data
#인간과 캠사이의 거리가 default 값이여야지, 두 위치 관계에 따라 달라짐

import cv2
import numpy as np

print("we are going to get data, position of eye please set up the Roi")
cap = cv2.VideoCapture(0)

rightComputerValue = [] #we are going to send the date, which is the position of eye
leftComputerValue = [] #we are going to send the date, which is the position of eye

while True:
    ret, frame = cap.read() 
    roi = frame
    
    rightRoi = frame[250:300,250:300] # if you want to change the roi, change this list[rows,cols]
    leftRoi = frame[250:300,300:350] # if you want to change the roi, change the list[rows,cols]
    
    roiGray = cv2.cvtColor(roi,cv2.COLOR_BGR2GRAY)
    rightRoiGray = cv2.cvtColor(rightRoi,cv2.COLOR_BGR2GRAY)
    leftROIGray = cv2.cvtColor(leftRoi,cv2.COLOR_BGR2GRAY)
    
    _, roiThreshold = cv2.threshold(roiGray,37,255,cv2.THRESH_BINARY_INV)
    _, rightThreshold = cv2.threshold(rightRoiGray,37,255,cv2.THRESH_BINARY_INV)
    _, leftThreshold = cv2.threshold(leftROIGray,37,255,cv2.THRESH_BINARY_INV)
    
    blurRoiThreshold = cv2.GaussianBlur(roiThreshold,(7,7),0)
    blurRightThreshold = cv2.GaussianBlur(rightThreshold,(7,7),0)
    blurLeftThreshold = cv2.GaussianBlur(leftThreshold,(7,7),0)
    
    rightContour,_ = cv2.findContours(blurRightThreshold,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    leftContour,_ = cv2.findContours(blurLeftThreshold,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    
    
    if ret:
        rows,cols,_ = roi.shape
        rightRows,rightCols,_ = rightRoi.shape
        leftRows,leftCols,_ = leftRoi.shape
        
        for rightCnt in rightContour:
            (x_r,y_r,w_r,h_r) = cv2.boundingRect(rightCnt)
            
            cv2.drawContours(rightRoi,[rightCnt],-1,(0,0,255),1)
            cv2.rectangle(rightRoi,(x_r,y_r),(x_r+w_r,y_r+h_r),(255,0,0),1)
            
            cv2.line(rightRoi,(x_r+int(w_r/2),0),(x_r+int(w_r/2),rightRows),(0,255,0),2)
            cv2.line(rightRoi,(0,y_r+int(h_r/2)),(rightCols,y_r+int(h_r/2)),(0,255,0),2)
        
        
        for leftCnt in leftContour:
            (x_l,y_l,w_l,h_l) = cv2.boundingRect(leftCnt)
            
            cv2.drawContours(leftRoi,[leftCnt],-1,(0,0,255),1)
            cv2.rectangle(leftRoi,(x_l,y_l),(x_l+w_l,y_l+h_l),(255,0,0),1)
            
            cv2.line(leftRoi,(x_l+int(w_l/2),0),(x_l+int(w_l/2),leftRows),(0,255,0),2)
            cv2.line(leftRoi,(0,y_l+int(h_l/2)),(leftCols,y_l+int(h_l/2)),(0,255,0),2)
        
        

        cv2.imshow("Roi",roi)
        cv2.imshow("rightEye",rightRoi)
        cv2.imshow("leftEye",leftRoi)
        cv2.imshow("roiBinary",blurRoiThreshold)
        cv2.imshow("rightBinary",blurRightThreshold)
        cv2.imshow("leftBinary",blurLeftThreshold)
        
        
        rightPosition=[x_r+int(w_r/2),y_r+int(h_r/2)]
        leftPosition=[x_l+int(w_l/2),y_l+int(h_l/2)]
        print("present right eye position",rightPosition,"\n present left eye position",leftPosition)
        
        rightComputerValue.append(rightPosition)
        leftComputerValue.append(leftPosition)
        
        key = cv2.waitKey(30) #if you want to change the time of frame change this waitKey(time)
        if key == 27:
            break
        
cap.release()            
cv2.destroyAllWindows()

print(rightComputerValue)
print(leftComputerValue)

#sendcode
def average(lst):
    """list in list->list #(inner list's lenth is 2)
    
    return the average of each index
    
    ex)
    >>>average([[0,5],[1,7],[2,9],[3,11],[4,13]])
    >>>[2,9] # float round 4
    """
    first, second = 0,0
    for k in lst:
        first += k[0]
        second += k[1]
        first_av = first/len(lst)
        second_av = second/len(lst)
    result = [round(first_av,4),round(second_av,4)]
    return result


rightComputerData = average(rightComputerValue)
leftComputerData = average(leftComputerValue)


while True:
    print("\n\n\n",rightComputerData,"is right Data")
    print(leftComputerData,"is left Data")
    whether = input("this Data is proper? y/n ")
    
    if whether == "y":
        with open("dataFile/rightComputerData.txt","a") as Rcomputer:
            with open("dataFile/leftComputerData.txt","a") as Lcomputer:
                with open("dataFile/realValue.txt","a") as real:
                    relative_coordinate_value = input("PLZ give me the position of relative coordinate value \n using csv value ex) 1,2,3 \n use meter unit")
                    
                    a=input(f"{relative_coordinate_value}is that True? y/n")
                    if a =="y":
                        Rcomputer.write(f"{rightComputerData[0]},{rightComputerData[1]}\n")
                        Lcomputer.write(f"{leftComputerData[0]},{leftComputerData[1]}\n")
                        real.write(f"{relative_coordinate_value}\n")
                        print("Data updated")
                        break
                    else:
                        continue
    elif whether == "n":
        break
    else:
        print("PLZ re try")
        continue
#(0 63 45)#위

we are going to get data, position of eye please set up the Roi
present right eye position [27, 35] 
 present left eye position [45, 37]
present right eye position [27, 36] 
 present left eye position [45, 38]
present right eye position [27, 37] 
 present left eye position [45, 38]
present right eye position [23, 37] 
 present left eye position [45, 38]
present right eye position [25, 36] 
 present left eye position [46, 38]
present right eye position [26, 36] 
 present left eye position [47, 38]
present right eye position [26, 36] 
 present left eye position [47, 38]
present right eye position [26, 36] 
 present left eye position [47, 38]
present right eye position [25, 36] 
 present left eye position [46, 38]
present right eye position [24, 36] 
 present left eye position [46, 38]
present right eye position [24, 36] 
 present left eye position [46, 37]
present right eye position [24, 36] 
 present left eye position [46, 37]
present right eye position [26, 36] 
 present left eye posit

present right eye position [11, 27] 
 present left eye position [37, 27]
present right eye position [12, 28] 
 present left eye position [37, 27]
present right eye position [12, 28] 
 present left eye position [37, 28]
present right eye position [16, 28] 
 present left eye position [37, 28]
present right eye position [13, 28] 
 present left eye position [38, 28]
present right eye position [13, 28] 
 present left eye position [38, 28]
present right eye position [17, 28] 
 present left eye position [38, 28]
present right eye position [17, 28] 
 present left eye position [38, 28]
present right eye position [17, 28] 
 present left eye position [39, 28]
present right eye position [22, 27] 
 present left eye position [40, 28]
present right eye position [23, 27] 
 present left eye position [41, 28]
present right eye position [22, 27] 
 present left eye position [41, 27]
present right eye position [23, 27] 
 present left eye position [41, 27]
present right eye position [23, 27] 
 present left 

present right eye position [18, 31] 
 present left eye position [39, 31]
present right eye position [18, 31] 
 present left eye position [39, 31]
present right eye position [18, 31] 
 present left eye position [39, 31]
present right eye position [18, 31] 
 present left eye position [39, 31]
present right eye position [18, 31] 
 present left eye position [39, 31]
present right eye position [18, 31] 
 present left eye position [38, 31]
present right eye position [17, 32] 
 present left eye position [38, 32]
present right eye position [17, 31] 
 present left eye position [38, 31]
present right eye position [17, 31] 
 present left eye position [38, 31]
present right eye position [18, 31] 
 present left eye position [38, 31]
present right eye position [18, 31] 
 present left eye position [38, 31]
present right eye position [19, 31] 
 present left eye position [39, 31]
present right eye position [20, 31] 
 present left eye position [39, 31]
present right eye position [15, 31] 
 present left 

this Data is proper? y/n y
PLZ give me the position of relative coordinate value 
 using csv value ex) 1,2,3 
 use meter unit0,7,0
0,7,0is that True? y/ny
Data updated


In [2]:
#if there any problem go data file and remove all 
# 만약 그림자 때문에 2개의 객체가 인식됐다면, 다시 하세요, #좀 더 업그레이드 해야할 듯
#좌측 상단의 꼭짓점의 좌표.



print("If you want to format the data, road this")
re = input("really? y/n")
if re == "y":
    with open("dataFile/rightComputerData.txt","w") as Rcomputer:
        with open("dataFile/leftComputerData.txt","w") as Lcomputer:
            with open("dataFile/realValue.txt","w") as real:
                Rcomputer.write("")
                Lcomputer.write("")
                real.write("")
                print("Data updated")
else:
    "Try again"
    

If you want to format the data, road this
really? y/ny
Data updated


In [63]:
#최소 제곱 근사를 이용한 

#다른 형태로 식을 추정할 수 있다면, 조명과 위치 값을 모두 고정하고 통계를 내보길 바란다. 기록하고,

# 지금 실험 모델에서는 눈의 중심으로부터 캠이 58cm 떨어져있다. 수평겨리로

import numpy as np

def changeFloat(lst):
    """list->list
    change string list to float list 
    """
    resultList=[]
    for k in lst:
        resultList.append(float(k))
    return resultList

#real vec{x}에 관한 방정식 유도,
with open("dataFile/rightComputerData.txt","r") as a:
    with open("dataFile/leftComputerData.txt","r") as b:
        with open("dataFile/realValue.txt","r") as c:
            Metrix=[]
            vec=[]
            for afileContent in a:
                bfileContent= ","+b.readline()
                testrow=afileContent+bfileContent
                stringrow = testrow.strip().split(",")
                row = changeFloat(stringrow)
                Metrix.append(row)
                stringImg = c.readline()
                lstImg = stringImg.strip().split(",")
                vec.append(changeFloat(lstImg)[0])
            
            V=np.array(Metrix)
            w=np.array(vec)
            print("Domain/ 정의역",V,"real의 x에 대한 열벡터",w,sep="\n")
            
            displace=np.dot(V.transpose(),V)
            displace2=np.dot(np.linalg.inv(displace),V.transpose())
            kernel = np.dot(displace2,w)
            print(kernel)
            print(f"다음 방정식을 최소제곱 근사 한 결과.\n {kernel[0]})x_r+{kernel[1]}y_r+{kernel[2]}x_l+{kernel[3]}y_l = vec(x)")
            print("식으로 근사 할 수 있다. \n\n\n\n")

with open("dataFile/rightComputerData.txt","r") as d:
    with open("dataFile/leftComputerData.txt","r") as e:
        with open("dataFile/realValue.txt","r") as f:
            Metrix=[]
            vec=[]
            for afileContent in d:
                bfileContent= ","+e.readline()
                testrow=afileContent+bfileContent
                stringrow = testrow.strip().split(",")
                row = changeFloat(stringrow)
                Metrix.append(row)
                stringImg = f.readline()
                lstImg = stringImg.strip().split(",")
                vec.append(changeFloat(lstImg)[1])
            
            V=np.array(Metrix)
            w=np.array(vec)
            print("Domain/ 정의역",V,"real의 x에 대한 열벡터",w,sep="\n")
            
            displace=np.dot(V.transpose(),V)
            displace2=np.dot(np.linalg.inv(displace),V.transpose())
            kernel = np.dot(displace2,w)
            print(kernel)
            print(f"다음 방정식을 최소제곱 근사 한 결과.\n {kernel[0]})x_r+{kernel[1]}y_r+{kernel[2]}x_l+{kernel[3]}y_l = vec(y)")
            print("식으로 근사 할 수 있다. \n\n\n\n")

with open("dataFile/rightComputerData.txt","r") as e:
    with open("dataFile/leftComputerData.txt","r") as f:
        with open("dataFile/realValue.txt","r") as g:
            Metrix=[]
            vec=[]
            for afileContent in e:
                bfileContent= ","+f.readline()
                testrow=afileContent+bfileContent
                stringrow = testrow.strip().split(",")
                row = changeFloat(stringrow)
                Metrix.append(row)
                stringImg = g.readline()
                lstImg = stringImg.strip().split(",")
                vec.append(changeFloat(lstImg)[2])
            
            V=np.array(Metrix)
            w=np.array(vec)
            print("Domain/ 정의역",V,"real의 x에 대한 열벡터",w,sep="\n")
            
            displace=np.dot(V.transpose(),V)
            displace2=np.dot(np.linalg.inv(displace),V.transpose())
            kernel = np.dot(displace2,w)
            print(kernel)
            print(f"다음 방정식을 최소제곱 근사 한 결과.\n {kernel[0]})x_r+{kernel[1]}y_r+{kernel[2]}x_l+{kernel[3]}y_l = vec(z)")
            print("식으로 근사 할 수 있다.")


Domain/ 정의역
[[18.9837 12.4674 34.5652 14.4185]
 [14.25   17.5372 20.6064 17.4202]
 [29.4106 14.2236 36.2236 15.2602]
 [21.3688 20.7234 34.227  20.7021]
 [12.2756 13.9843 30.1732 14.3228]
 [19.044  28.326  39.     28.8352]]
real의 x에 대한 열벡터
[-75.  46.   0.   0.   0.   0.]
[  2.56410784  39.2803433   -1.80713928 -37.79767225]
다음 방정식을 최소제곱 근사 한 결과.
 2.5641078443147274)x_r+39.280343296081575y_r+-1.8071392830124375x_l+-37.79767225128475y_l = vec(x)
식으로 근사 할 수 있다. 




Domain/ 정의역
[[18.9837 12.4674 34.5652 14.4185]
 [14.25   17.5372 20.6064 17.4202]
 [29.4106 14.2236 36.2236 15.2602]
 [21.3688 20.7234 34.227  20.7021]
 [12.2756 13.9843 30.1732 14.3228]
 [19.044  28.326  39.     28.8352]]
real의 x에 대한 열벡터
[10. 31. 40. 92. 63.  7.]
[ -0.14924861  59.47813202   5.83761712 -65.45479227]
다음 방정식을 최소제곱 근사 한 결과.
 -0.1492486109221498)x_r+59.478132023955595y_r+5.83761712377559x_l+-65.4547922745532y_l = vec(y)
식으로 근사 할 수 있다. 




Domain/ 정의역
[[18.9837 12.4674 34.5652 14.4185]
 [14.25   17.5372 20.6064 17